language: node_js
node_js:
    - "0.10"
    - "0.11"
    - "0.12"
addons:
    code_climate:
        repo_token: b7a5acc3dc8f3d8e43648baf83d77d9954f6077e55032dbd763fbe30d7924140
install:
    - npm install -g grunt-cli
    - npm install -g codeclimate-test-reporter
    - npm install
script:
    - grunt
after_script:
    - CODECLIMATE_REPO_TOKEN=3ffe577d8ce67dbf78d34cc3cce3ce602d33d9b9f11c689feb04f0cb77e487c8 codeclimate < ./coverage/lcov.info